// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressTracker.Data;

#nullable disable

namespace ProgressTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250315190752_taskObjectiveRelationship")]
    partial class taskObjectiveRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgressTracker.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("ProgressTracker.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasDiscriminator<string>("TaskType").HasValue("Task");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgressTracker.Models.LargeTask", b =>
                {
                    b.HasBaseType("ProgressTracker.Models.Task");

                    b.HasDiscriminator().HasValue("LargeTask");
                });

            modelBuilder.Entity("ProgressTracker.Models.MediumTask", b =>
                {
                    b.HasBaseType("ProgressTracker.Models.Task");

                    b.HasDiscriminator().HasValue("MediumTask");
                });

            modelBuilder.Entity("ProgressTracker.Models.SmallTask", b =>
                {
                    b.HasBaseType("ProgressTracker.Models.Task");

                    b.HasDiscriminator().HasValue("SmallTask");
                });

            modelBuilder.Entity("ProgressTracker.Models.Objective", b =>
                {
                    b.HasOne("ProgressTracker.Models.Task", "Task")
                        .WithMany("Objectives")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ProgressTracker.Models.Task", b =>
                {
                    b.Navigation("Objectives");
                });
#pragma warning restore 612, 618
        }
    }
}
